// Code generated by Kitex v0.5.0. DO NOT EDIT.

package helloservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	hello "primus/kitex_gen/hello"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Echo(ctx context.Context, req *hello.Request, callOptions ...callopt.Option) (r *hello.Response, err error)
	Get(ctx context.Context, callOptions ...callopt.Option) (r *hello.Response, err error)
	GetByParams(ctx context.Context, data string, msg string, callOptions ...callopt.Option) (r *hello.Response, err error)
	GetH(ctx context.Context, id int32, callOptions ...callopt.Option) (r *hello.Response, err error)
	Post(ctx context.Context, req *hello.Request, callOptions ...callopt.Option) (r *hello.Response, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kHelloServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kHelloServiceClient struct {
	*kClient
}

func (p *kHelloServiceClient) Echo(ctx context.Context, req *hello.Request, callOptions ...callopt.Option) (r *hello.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Echo(ctx, req)
}

func (p *kHelloServiceClient) Get(ctx context.Context, callOptions ...callopt.Option) (r *hello.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Get(ctx)
}

func (p *kHelloServiceClient) GetByParams(ctx context.Context, data string, msg string, callOptions ...callopt.Option) (r *hello.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetByParams(ctx, data, msg)
}

func (p *kHelloServiceClient) GetH(ctx context.Context, id int32, callOptions ...callopt.Option) (r *hello.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetH(ctx, id)
}

func (p *kHelloServiceClient) Post(ctx context.Context, req *hello.Request, callOptions ...callopt.Option) (r *hello.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Post(ctx, req)
}
