// Code generated by hertz generator.

package hello

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _postMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getbyparamsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getbyparams0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gethMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _geth0Mw() []app.HandlerFunc {
	// your code...
	return nil
}
