// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"primus/customer-service/biz/router"
)

func main() {
	h := server.Default(
		server.WithHostPorts(":9809"),
	)

	router.GeneratedRegister(h)
	h.Spin()
}
